from typing import Optional, List, Dict, Any
from pydantic import Field
from .base import ApolloModel

class OrganizationEnrichmentQuery(ApolloModel):
    domain: str = Field(description="The domain of the company that you want to enrich. Do not include `www.`, the `@` symbol, or similar. Example: `apollo.io` or `microsoft.com`")

class PrimaryPhone(ApolloModel):
    languages: Optional[List[str]] = Field(default=None, description="languages")
    phone: Optional[str] = Field(default=None, description="phone")

class FundingEvent(ApolloModel):
    id: Optional[str] = Field(default=None, description="id")
    date: Optional[str] = Field(default=None, description="date")
    news_url: Optional[str] = Field(default=None, description="news_url")
    type: Optional[str] = Field(default=None, description="type")
    investors: Optional[str] = Field(default=None, description="investors")
    amount: Optional[str] = Field(default=None, description="amount")
    currency: Optional[str] = Field(default=None, description="currency")

class Account(ApolloModel):
    id: Optional[str] = Field(default=None, description="id")
    domain: Optional[str] = Field(default=None, description="domain")
    name: Optional[str] = Field(default=None, description="name")
    team_id: Optional[str] = Field(default=None, description="team_id")
    organization_id: Optional[str] = Field(default=None, description="organization_id")
    account_stage_id: Optional[str] = Field(default=None, description="account_stage_id")
    source: Optional[str] = Field(default=None, description="source")
    original_source: Optional[str] = Field(default=None, description="original_source")
    creator_id: Optional[str] = Field(default=None, description="creator_id")
    owner_id: Optional[str] = Field(default=None, description="owner_id")
    created_at: Optional[str] = Field(default=None, description="created_at")
    phone: Optional[str] = Field(default=None, description="phone")
    phone_status: Optional[str] = Field(default=None, description="phone_status")
    hubspot_id: Optional[str] = Field(default=None, description="hubspot_id")
    salesforce_id: Optional[str] = Field(default=None, description="salesforce_id")
    crm_owner_id: Optional[str] = Field(default=None, description="crm_owner_id")
    parent_account_id: Optional[str] = Field(default=None, description="parent_account_id")
    linkedin_url: Optional[str] = Field(default=None, description="linkedin_url")
    sanitized_phone: Optional[str] = Field(default=None, description="sanitized_phone")
    account_playbook_statuses: List[Any] = Field(default_factory=list, description="account_playbook_statuses")
    account_rule_config_statuses: List[Any] = Field(default_factory=list, description="account_rule_config_statuses")
    existence_level: Optional[str] = Field(default=None, description="existence_level")
    label_ids: List[Any] = Field(default_factory=list, description="label_ids")
    typed_custom_fields: Optional[Dict[str, Any]] = Field(default=None, description="typed_custom_fields")
    custom_field_errors: Optional[Dict[str, Any]] = Field(default=None, description="custom_field_errors")
    modality: Optional[str] = Field(default=None, description="modality")
    source_display_name: Optional[str] = Field(default=None, description="source_display_name")
    crm_record_url: Optional[str] = Field(default=None, description="crm_record_url")
    intent_strength: Optional[str] = Field(default=None, description="intent_strength")
    show_intent: Optional[bool] = Field(default=None, description="show_intent")
    has_intent_signal_account: Optional[bool] = Field(default=None, description="has_intent_signal_account")
    intent_signal_signal_account: Optional[str] = Field(default=None, description="intent_signal_signal_account")

class DepartmentalHeadCount(ApolloModel):
    engineering: Optional[int] = Field(default=None, description="engineering")
    operations: Optional[int] = Field(default=None, description="operations")
    support: Optional[int] = Field(default=None, description="support")
    marketing: Optional[int] = Field(default=None, description="marketing")
    human_resources: Optional[int] = Field(default=None, description="human_resources")
    sales: Optional[int] = Field(default=None, description="sales")
    finance: Optional[int] = Field(default=None, description="finance")
    consulting: Optional[int] = Field(default=None, description="consulting")
    legal: Optional[int] = Field(default=None, description="legal")
    arts_and_design: Optional[int] = Field(default=None, description="arts_and_design")
    accounting: Optional[int] = Field(default=None, description="accounting")
    business_development: Optional[int] = Field(default=None, description="business_development")
    information_technology: Optional[int] = Field(default=None, description="information_technology")
    education: Optional[int] = Field(default=None, description="education")
    media_and_commmunication: Optional[int] = Field(default=None, description="media_and_commmunication")
    product_management: Optional[int] = Field(default=None, description="product_management")
    entrepreneurship: Optional[int] = Field(default=None, description="entrepreneurship")
    data_science: Optional[int] = Field(default=None, description="data_science")
    administrative: Optional[int] = Field(default=None, description="administrative")

class CurrentTechnology(ApolloModel):
    uid: str = Field(description="uid")
    name: str = Field(description="name")
    category: str = Field(description="category")

class IndustryTagHash(ApolloModel):
    information_technology_services: Optional[str] = Field(default=None, description="information_technology_services")

class Organization(ApolloModel):
    id: Optional[str] = Field(default=None, description="id")
    name: Optional[str] = Field(default=None, description="name")
    website_url: Optional[str] = Field(default=None, description="website_url")
    blog_url: Optional[str] = Field(default=None, description="blog_url")
    angellist_url: Optional[str] = Field(default=None, description="angellist_url")
    linkedin_url: Optional[str] = Field(default=None, description="linkedin_url")
    twitter_url: Optional[str] = Field(default=None, description="twitter_url")
    facebook_url: Optional[str] = Field(default=None, description="facebook_url")
    primary_phone: Optional[PrimaryPhone] = Field(default=None, description="primary_phone")
    languages: Optional[List[Any]] = Field(default=None, description="languages")
    alexa_ranking: Optional[int] = Field(default=0, description="alexa_ranking")
    phone: Optional[str] = Field(default=None, description="phone")
    linkedin_uid: Optional[str] = Field(default=None, description="linkedin_uid")
    founded_year: Optional[int] = Field(default=0, description="founded_year")
    publicly_traded_symbol: Optional[str] = Field(default=None, description="publicly_traded_symbol")
    publicly_traded_exchange: Optional[str] = Field(default=None, description="publicly_traded_exchange")
    logo_url: Optional[str] = Field(default=None, description="logo_url")
    crunchbase_url: Optional[str] = Field(default=None, description="crunchbase_url")
    primary_domain: Optional[str] = Field(default=None, description="primary_domain")
    industry: Optional[str] = Field(default=None, description="industry")
    keywords: List[str] = Field(default_factory=list, description="keywords")
    estimated_num_employees: Optional[int] = Field(default=0, description="estimated_num_employees")
    industries: List[str] = Field(default_factory=list, description="industries")
    secondary_industries: List[Any] = Field(default_factory=list, description="secondary_industries")
    snippets_loaded: Optional[bool] = Field(default=None, description="snippets_loaded")
    industry_tag_id: Optional[str] = Field(default=None, description="industry_tag_id")
    industry_tag_hash: Optional[Any] = Field(default=None, description="industry_tag_hash")
    retail_location_count: Optional[int] = Field(default=0, description="retail_location_count")
    raw_address: Optional[str] = Field(default=None, description="raw_address")
    street_address: Optional[str] = Field(default=None, description="street_address")
    city: Optional[str] = Field(default=None, description="city")
    state: Optional[str] = Field(default=None, description="state")
    postal_code: Optional[str] = Field(default=None, description="postal_code")
    country: Optional[str] = Field(default=None, description="country")
    owned_by_organization_id: Optional[str] = Field(default=None, description="owned_by_organization_id")
    seo_description: Optional[str] = Field(default=None, description="seo_description")
    short_description: Optional[str] = Field(default=None, description="short_description")
    suborganizations: List[Any] = Field(default_factory=list, description="suborganizations")
    num_suborganizations: Optional[int] = Field(default=0, description="num_suborganizations")
    annual_revenue_printed: Optional[str] = Field(default=None, description="annual_revenue_printed")
    annual_revenue: Optional[int] = Field(default=0, description="annual_revenue")
    total_funding: Optional[int] = Field(default=None, description="total_funding")
    total_funding_printed: Optional[str] = Field(default=None, description="total_funding_printed")
    latest_funding_round_date: Optional[str] = Field(default=None, description="latest_funding_round_date")
    latest_funding_stage: Optional[str] = Field(default=None, description="latest_funding_stage")
    funding_events: Optional[List[FundingEvent]] = Field(default=None, description="funding_events")
    technology_names: List[str] = Field(default_factory=list, description="technology_names")
    current_technologies: List[Any] = Field(default_factory=list, description="current_technologies")
    org_chart_root_people_ids: List[str] = Field(default_factory=list, description="org_chart_root_people_ids")
    org_chart_sector: Optional[str] = Field(default=None, description="org_chart_sector")
    org_chart_removed: bool = Field(default=True, description="org_chart_removed")
    org_chart_show_department_filter: bool = Field(default=True, description="org_chart_show_department_filter")
    account_id: Optional[str] = Field(default=None, description="account_id")
    account: Optional[Account] = Field(default=None, description="account")
    departmental_head_count: Optional[Any] = Field(default=None, description="departmental_head_count")

class OrganizationEnrichmentResponse(ApolloModel):
    organization: Organization = Field(description="organization")
