from typing import Optional, List, Dict, Any
from pydantic import Field
from .base import ApolloModel

class PeopleEnrichmentQuery(ApolloModel):
    first_name: Optional[str] = Field(default=None, description="The first name of the person. This is typically used in combination with the `last_name` parameter. Example: `tim`")
    last_name: Optional[str] = Field(default=None, description="The last name of the person. This is typically used in combination with the `first_name` parameter. Example: `zheng`")
    name: Optional[str] = Field(default=None, description="The full name of the person. This will typically be a first name and last name separated by a space. If you use this parameter, you do not need to use the `first_name` and `last_name` parameters. Example: `tim zheng`")
    email: Optional[str] = Field(default=None, description="The email address of the person. Example: `example@email.com`")
    hashed_email: Optional[str] = Field(default=None, description="The hashed email of the person. The email should adhere to either the MD5 or SHA-256 hash format. Example: `8d935115b9ff4489f2d1f9249503cadf` (MD5) or `97817c0c49994eb500ad0a5e7e2d8aed51977b26424d508f66e4e8887746a152` (SHA-256)")
    organization_name: Optional[str] = Field(default=None, description="The name of the person's employer. This can be the current employer or a previous employer. Example: `apollo`")
    domain: Optional[str] = Field(default=None, description="The domain name for the person's employer. This can be the current employer or a previous employer. Do not include `www.`, the `@` symbol, or similar. Example: `apollo.io` or `microsoft.com`")
    id: Optional[str] = Field(default=None, description="The Apollo ID for the person. Each person in the Apollo database is assigned a unique ID. To find IDs, call the [People Search endpoint](/reference/people-search) and identify the values for `person_id`. Example: `587cf802f65125cad923a266`")
    linkedin_url: Optional[str] = Field(default=None, description="The URL for the person's LinkedIn profile. Example: `http://www.linkedin.com/in/tim-zheng-677ba010`")
    reveal_personal_emails: Optional[bool] = Field(default=False, description="Set to `true` if you want to enrich the person's data with personal emails. This potentially consumes credits as part of your [Apollo pricing plan](/docs/api-pricing). The default value is `false`. If a person resides in a [GDPR](https://knowledge.apollo.io/hc/en-us/articles/4409141087757)-compliant region, Apollo will not reveal their personal email.")
    reveal_phone_number: Optional[bool] = Field(default=False, description="Set to `true` if you want to enrich the person's data with all available phone numbers, including mobile phone numbers. This potentially consumes credits as part of your [Apollo pricing plan](/docs/api-pricing). The default value is `false`. If this parameter is set to `true`, you must enter a webhook URL for the `webhook_url` parameter. Apollo will asynchronously verify phone numbers for you, then send a JSON response that includes only details about the person's phone numbers to the webhook URL you provide. It can take several minutes for the phone numbers to be delivered.")
    webhook_url: Optional[str] = Field(default=None, description="If you set the `reveal_phone_number` parameter to `true`, this parameter becomes mandatory. Otherwise, do not use this parameter. Enter the webhook URL that specifies where Apollo should send a JSON response that includes the phone number you requested. Apollo suggests testing this flow to ensure you receive the separate response with the phone number. Example: `https://webhook.site/cc4cf44e-e047-4774-8dac-473d28474e40`")

class EmploymentHistory(ApolloModel):
    id: Optional[str] = Field(default=None, description="id")
    created_at: Optional[str] = Field(default=None, description="created_at")
    current: Optional[bool] = Field(default=None, description="current")
    degree: Optional[str] = Field(default=None, description="degree")
    description: Optional[str] = Field(default=None, description="description")
    emails: Optional[Any] = Field(default=None, description="emails")
    end_date: Optional[str] = Field(default=None, description="end_date")
    grade_level: Optional[str] = Field(default=None, description="grade_level")
    kind: Optional[str] = Field(default=None, description="kind")
    major: Optional[str] = Field(default=None, description="major")
    organization_id: Optional[str] = Field(default=None, description="organization_id")
    organization_name: Optional[str] = Field(default=None, description="organization_name")
    raw_address: Optional[str] = Field(default=None, description="raw_address")
    start_date: Optional[str] = Field(default=None, description="start_date")
    title: Optional[str] = Field(default=None, description="title")
    updated_at: Optional[str] = Field(default=None, description="updated_at")
    key: Optional[str] = Field(default=None, description="key")
    state: Optional[str] = Field(default=None, description="state")
    city: Optional[str] = Field(default=None, description="city")
    country: Optional[str] = Field(default=None, description="country")
    contact_id: Optional[str] = Field(default=None, description="contact_id")

class Contact(ApolloModel):
    contact_roles: List[Any] = Field(default_factory=list, description="contact_roles")
    id: Optional[str] = Field(default=None, description="id")
    first_name: Optional[str] = Field(default=None, description="first_name")
    last_name: Optional[str] = Field(default=None, description="last_name")
    name: Optional[str] = Field(default=None, description="name")
    linkedin_url: Optional[str] = Field(default=None, description="linkedin_url")
    title: Optional[str] = Field(default=None, description="title")
    contact_stage_id: Optional[str] = Field(default=None, description="contact_stage_id")
    owner_id: Optional[str] = Field(default=None, description="owner_id")
    creator_id: Optional[str] = Field(default=None, description="creator_id")
    person_id: Optional[str] = Field(default=None, description="person_id")
    email_needs_tickling: Optional[bool] = Field(default=None, description="email_needs_tickling")
    organization_name: Optional[str] = Field(default=None, description="organization_name")
    source: Optional[str] = Field(default=None, description="source")
    original_source: Optional[str] = Field(default=None, description="original_source")
    organization_id: Optional[str] = Field(default=None, description="organization_id")
    headline: Optional[str] = Field(default=None, description="headline")
    photo_url: Optional[str] = Field(default=None, description="photo_url")
    present_raw_address: Optional[str] = Field(default=None, description="present_raw_address")
    linkedin_uid: Optional[str] = Field(default=None, description="linkedin_uid")
    extrapolated_email_confidence: Optional[Any] = Field(default=None, description="extrapolated_email_confidence")
    salesforce_id: Optional[str] = Field(default=None, description="salesforce_id")
    salesforce_lead_id: Optional[str] = Field(default=None, description="salesforce_lead_id")
    salesforce_contact_id: Optional[str] = Field(default=None, description="salesforce_contact_id")
    salesforce_account_id: Optional[str] = Field(default=None, description="salesforce_account_id")
    crm_owner_id: Optional[str] = Field(default=None, description="crm_owner_id")
    created_at: Optional[str] = Field(default=None, description="created_at")
    emailer_campaign_ids: List[Any] = Field(default_factory=list, description="emailer_campaign_ids")
    direct_dial_status: Optional[str] = Field(default=None, description="direct_dial_status")
    direct_dial_enrichment_failed_at: Optional[str] = Field(default=None, description="direct_dial_enrichment_failed_at")
    email_status: Optional[str] = Field(default=None, description="email_status")
    email_source: Optional[str] = Field(default=None, description="email_source")
    account_id: Optional[str] = Field(default=None, description="account_id")
    last_activity_date: Optional[str] = Field(default=None, description="last_activity_date")
    hubspot_vid: Optional[str] = Field(default=None, description="hubspot_vid")
    hubspot_company_id: Optional[str] = Field(default=None, description="hubspot_company_id")
    crm_id: Optional[str] = Field(default=None, description="crm_id")
    sanitized_phone: Optional[str] = Field(default=None, description="sanitized_phone")
    merged_crm_ids: Optional[Any] = Field(default=None, description="merged_crm_ids")
    updated_at: Optional[str] = Field(default=None, description="updated_at")
    queued_for_crm_push: Optional[Any] = Field(default=None, description="queued_for_crm_push")
    suggested_from_rule_engine_config_id: Optional[str] = Field(default=None, description="suggested_from_rule_engine_config_id")
    email_unsubscribed: Optional[bool] = Field(default=None, description="email_unsubscribed")
    label_ids: List[Any] = Field(default_factory=list, description="label_ids")
    has_pending_email_arcgate_request: Optional[bool] = Field(default=None, description="has_pending_email_arcgate_request")
    has_email_arcgate_request: Optional[bool] = Field(default=None, description="has_email_arcgate_request")
    existence_level: Optional[str] = Field(default=None, description="existence_level")
    email: Optional[str] = Field(default=None, description="email")
    email_from_customer: Optional[bool] = Field(default=None, description="email_from_customer")
    typed_custom_fields: Optional[Dict[str, Any]] = Field(default=None, description="typed_custom_fields")
    custom_field_errors: Optional[Any] = Field(default=None, description="custom_field_errors")
    crm_record_url: Optional[str] = Field(default=None, description="crm_record_url")
    email_status_unavailable_reason: Optional[str] = Field(default=None, description="email_status_unavailable_reason")
    email_true_status: Optional[str] = Field(default=None, description="email_true_status")
    updated_email_true_status: Optional[bool] = Field(default=None, description="updated_email_true_status")
    contact_rule_config_statuses: List[Any] = Field(default_factory=list, description="contact_rule_config_statuses")
    source_display_name: Optional[str] = Field(default=None, description="source_display_name")
    contact_emails: List[Dict[str, Any]] = Field(default_factory=list, description="contact_emails")
    time_zone: Optional[str] = Field(default=None, description="time_zone")
    phone_numbers: List[Dict[str, Any]] = Field(default_factory=list, description="phone_numbers")
    account_phone_note: Optional[str] = Field(default=None, description="account_phone_note")
    free_domain: Optional[bool] = Field(default=None, description="free_domain")
    is_likely_to_engage: Optional[bool] = Field(default=None, description="is_likely_to_engage")

class Organization(ApolloModel):
    id: Optional[str] = Field(default=None, description="id")
    name: Optional[str] = Field(default=None, description="name")
    website_url: Optional[str] = Field(default=None, description="website_url")
    blog_url: Optional[str] = Field(default=None, description="blog_url")
    angellist_url: Optional[str] = Field(default=None, description="angellist_url")
    linkedin_url: Optional[str] = Field(default=None, description="linkedin_url")
    twitter_url: Optional[str] = Field(default=None, description="twitter_url")
    facebook_url: Optional[str] = Field(default=None, description="facebook_url")
    primary_phone: Optional[Dict[str, Any]] = Field(default=None, description="primary_phone")
    languages: List[Any] = Field(default_factory=list, description="languages")
    alexa_ranking: Optional[int] = Field(default=None, description="alexa_ranking")
    phone: Optional[str] = Field(default=None, description="phone")
    linkedin_uid: Optional[str] = Field(default=None, description="linkedin_uid")
    founded_year: Optional[int] = Field(default=None, description="founded_year")
    publicly_traded_symbol: Optional[str] = Field(default=None, description="publicly_traded_symbol")
    publicly_traded_exchange: Optional[str] = Field(default=None, description="publicly_traded_exchange")
    logo_url: Optional[str] = Field(default=None, description="logo_url")
    crunchbase_url: Optional[str] = Field(default=None, description="crunchbase_url")
    primary_domain: Optional[str] = Field(default=None, description="primary_domain")
    industry: Optional[str] = Field(default=None, description="industry")
    keywords: List[str] = Field(default_factory=list, description="keywords")
    estimated_num_employees: Optional[int] = Field(default=None, description="estimated_num_employees")
    industries: List[str] = Field(default_factory=list, description="industries")
    secondary_industries: List[Any] = Field(default_factory=list, description="secondary_industries")
    snippets_loaded: Optional[bool] = Field(default=None, description="snippets_loaded")
    industry_tag_id: Optional[str] = Field(default=None, description="industry_tag_id")
    industry_tag_hash: Optional[Dict[str, str]] = Field(default=None, description="industry_tag_hash")
    retail_location_count: Optional[int] = Field(default=0, description="retail_location_count")
    raw_address: Optional[str] = Field(default=None, description="raw_address")
    street_address: Optional[str] = Field(default=None, description="street_address")
    city: Optional[str] = Field(default=None, description="city")
    state: Optional[str] = Field(default=None, description="state")
    postal_code: Optional[str] = Field(default=None, description="postal_code")
    country: Optional[str] = Field(default=None, description="country")
    owned_by_organization_id: Optional[str] = Field(default=None, description="owned_by_organization_id")
    seo_description: Optional[str] = Field(default=None, description="seo_description")
    short_description: Optional[str] = Field(default=None, description="short_description")
    suborganizations: List[Any] = Field(default_factory=list, description="suborganizations")
    num_suborganizations: Optional[int] = Field(default=0, description="num_suborganizations")
    annual_revenue_printed: Optional[str] = Field(default=None, description="annual_revenue_printed")
    annual_revenue: Optional[int] = Field(default=None, description="annual_revenue")
    total_funding: Optional[int] = Field(default=None, description="total_funding")
    total_funding_printed: Optional[str] = Field(default=None, description="total_funding_printed")
    latest_funding_round_date: Optional[str] = Field(default=None, description="latest_funding_round_date")
    latest_funding_stage: Optional[str] = Field(default=None, description="latest_funding_stage")
    funding_events: List[Dict[str, Any]] = Field(default_factory=list, description="funding_events")
    technology_names: List[str] = Field(default_factory=list, description="technology_names")
    current_technologies: List[Dict[str, Any]] = Field(default_factory=list, description="current_technologies")
    org_chart_root_people_ids: List[str] = Field(default_factory=list, description="org_chart_root_people_ids")
    org_chart_sector: Optional[str] = Field(default=None, description="org_chart_sector")
    org_chart_removed: Optional[bool] = Field(default=None, description="org_chart_removed")
    org_chart_show_department_filter: Optional[bool] = Field(default=None, description="org_chart_show_department_filter")

class PeopleEnrichmentResponse(ApolloModel):
    person: Optional["Person"] = None

class Person(ApolloModel):
    id: str = Field(description="id")
    first_name: str = Field(description="first_name")
    last_name: str = Field(description="last_name")
    name: str = Field(description="name")
    linkedin_url: Optional[str] = Field(default=None, description="linkedin_url")
    title: Optional[str] = Field(default=None, description="title")
    email_status: Optional[str] = Field(default=None, description="email_status")
    photo_url: Optional[str] = Field(default=None, description="photo_url")
    twitter_url: Optional[str] = Field(default=None, description="twitter_url")
    github_url: Optional[str] = Field(default=None, description="github_url")
    facebook_url: Optional[str] = Field(default=None, description="facebook_url")
    extrapolated_email_confidence: Optional[str] = Field(default=None, description="extrapolated_email_confidence")
    headline: Optional[str] = Field(description="headline")
    email: Optional[str] = Field(description="email")
    organization_id: Optional[str] = Field(description="organization_id")
    employment_history: List[EmploymentHistory] = Field(description="employment_history")
    state: Optional[str] = Field(default=None, description="state")
    city: Optional[str] = Field(default=None, description="city")
    country: Optional[str] = Field(default=None, description="country")
    contact_id: Optional[str] = Field(default=None, description="contact_id")
    contact: Optional[Contact] = Field(default=None, description="contact")
    revealed_for_current_team: bool = Field(description="revealed_for_current_team")
    organization: Optional[Organization] = Field(default=None, description="organization")
    is_likely_to_engage: Optional[bool] = Field(default=None, description="is_likely_to_engage")
    intent_strength: Optional[str] = Field(default=None, description="intent_strength")
    show_intent: bool = Field(description="show_intent")
    departments: List[str] = Field(description="departments")
    subdepartments: List[str] = Field(description="subdepartments")
    functions: List[str] = Field(description="functions")
    seniority: Optional[str] = Field(description="seniority")
